apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nginx-frontend-servicemonitor
  namespace: monitoring
  labels:
    release: prometheus   
spec:
  namespaceSelector:
    matchNames:
      - webapp
  selector:
    matchLabels:
      app: nginx-frontend
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
