# Kubernetes - NGINX-FRONTEND - Service Definition Manifest file
apiVersion: v1
kind: Service
metadata:
   name: nginx-frontend
   namespace: webapp
   labels: 
      app: nginx-frontend
      tier: tier0
      type: frontend

spec:
  selector: 
      app: nginx-frontend
  type: LoadBalancer
  ports:
    - name: tcp
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
    
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: 9113


